trigger:
- vsts/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/master

phases:
- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: Windows
    buildArgs: /p:VSTestVerboseOutput=true
    afterBuild:
    - task: PublishBuildArtifacts@1
      displayName: Upload build logs
      condition: and(always(), eq(variables['system.pullrequest.isfork'], false))
      inputs:
        pathtoPublish: 'artifacts/logs/'
        artifactName: logs-$(AgentOsName)-$(BuildConfiguration)
        artifactType: Container

